import { nimChat } from "./ai.service";
import { getResumeData } from "./resumeGenerator.service";
import puppeteer from "puppeteer-core";
import chromium from "@sparticuz/chromium";
import { AlignmentType, Document, Packer, Paragraph, TextRun } from "docx";
import { BadRequestError } from "../utils/errors";

export type CoverLetterStyle = "CLASSIC" | "MODERN" | "CREATIVE" | "MINIMALIST";

export interface GenerateCoverLetterArgs {
  userId: string;
  jobTitle: string;
  companyName: string;
  jobDescription?: string;
  style: CoverLetterStyle;
}

export interface RenderCoverLetterArgs {
  fullName: string;
  email: string;
  phoneNumber?: string;
  headline?: string;
  style: CoverLetterStyle;
  content: string;
  jobTitle: string;
  companyName: string;
  themeColor?: string;
}

// Map styles to theme colors if applicable
const STYLE_COLOR_MAP: Record<CoverLetterStyle, string> = {
  CLASSIC: "#1e293b",
  MODERN: "#2563eb",
  CREATIVE: "#d97706",
  MINIMALIST: "#111111",
};

export async function composeCoverLetter(args: GenerateCoverLetterArgs): Promise<string> {
  const { userId, jobTitle, companyName, jobDescription, style } = args;

  if (!jobTitle.trim() || !companyName.trim()) {
    throw new BadRequestError("Job title and company name are required.");
  }

  // Fetch candidate's background data
  const data = await getResumeData(userId);
  const { user, experiences, projects, educations, socialLinks } = data;
  const profile = user.profile;

  // Format experience bullet summaries for prompt injection
  const experienceSummary = experiences
    .map((exp) => {
      const bullets = Array.isArray(exp.bullets) ? (exp.bullets as string[]) : [];
      return `- ${exp.role} at ${exp.company} (${exp.startDate.getFullYear()} - ${exp.endDate ? exp.endDate.getFullYear() : "Present"}):\n${bullets.map(b => `  * ${b}`).join("\n")}`;
    })
    .join("\n\n");

  // Format projects
  const projectSummary = projects
    .map((p) => `- Project: ${p.title} (${p.description || ""})`)
    .join("\n");

  // Format skills
  const skillsList = profile?.techStacks
    ? profile.techStacks.map((s) => s.tech.name).join(", ")
    : "";

  const systemPrompt = `You are an elite, persuasive career consultant and cover letter writer. 
Write a highly targeted, professional, and quantified cover letter that perfectly aligns the candidate's background with the job description.
Follow these rules strictly:
1. Address the hiring manager or recruitment team professionally.
2. Ensure the entire cover letter (including salutation, body, and sign-off) is between 300 to 400 words total, structured as 3-4 professional, impactful paragraphs:
   - Paragraph 1: Catchy opening identifying the role of "${jobTitle}" at "${companyName}", and why the candidate is exceptionally excited.
   - Paragraph 2: Core technical/analytical match highlighting 1-2 key, highly quantified achievements from their experience.
   - Paragraph 3: Cultural fit, soft skills, and alignment with the role's requirements.
   - Paragraph 4: Enthusiastic closing call-to-action requesting an interview.
3. Match the chosen tone/style:
   - CLASSIC: Formal, elegant, traditional, and highly professional.
   - MODERN: Direct, technical, bold, and high-impact.
   - CREATIVE: Dynamic, narrative, passionate, and slightly bold.
   - MINIMALIST: Short, punchy, laser-focused on core strengths.
4. Output ONLY the raw cover letter body text (no address blocks, dates, header details, or footer sign-offs in the generated string, as they are automatically generated by the layout templates). Start directly with 'Dear [Hiring Manager/Team],' and end with the closing sign-off and candidate's name.`;

  const userPrompt = [
    `Please compose a tailored cover letter for:`,
    `Role: ${jobTitle}`,
    `Company: ${companyName}`,
    jobDescription ? `Job Description: ${jobDescription}` : `No detailed job description provided. Align with standard requirements for this role.`,
    `Candidate Profile:`,
    `- Name: ${profile?.displayName || user.fullName}`,
    `- Headline: ${profile?.headline || "Software Engineer"}`,
    `- Professional Bio: ${profile?.bio || ""}`,
    `- Top Skills: ${skillsList}`,
    `Candidate Experience:\n${experienceSummary}`,
    `Candidate Projects:\n${projectSummary}`,
    `Style Preference: ${style}`,
  ].join("\n\n");

  const letterText = await nimChat([
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt }
  ], { maxTokens: 1000, temperature: 0.7 });

  return letterText.trim();
}

function escapeHtml(input: string | null | undefined) {
  if (!input) return "";
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatLetterContentHtml(content: string): string {
  // Split paragraphs by double newlines and wrap in <p> tags
  return content
    .split(/\n\s*\n/)
    .map(p => `<p style="margin-bottom: 12px;">${escapeHtml(p.trim())}</p>`)
    .join("\n");
}

export function buildCoverLetterHtml(args: RenderCoverLetterArgs): string {
  const { fullName, email, phoneNumber, headline, style, content, jobTitle, companyName, themeColor } = args;
  const accentColor = themeColor || STYLE_COLOR_MAP[style];
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric"
  });

  const formattedParagraphs = formatLetterContentHtml(content);

  switch (style) {
    case "MODERN":
      return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: Letter; margin: 0.6in 0.8in; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 9.5pt; color: #1e293b; line-height: 1.5; }
    .header { margin-bottom: 20px; padding-bottom: 12px; border-bottom: 2px solid ${accentColor}; }
    .name { font-size: 20pt; font-weight: 800; color: #0f172a; tracking: -0.03em; line-height: 1.1; }
    .headline { font-size: 9.5pt; color: ${accentColor}; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 3px; }
    .contact-info { display: flex; flex-wrap: wrap; gap: 15px; margin-top: 8px; font-size: 8pt; color: #64748b; }
    .contact-item { display: flex; align-items: center; }
    .recipient-info { margin-bottom: 15px; font-size: 9pt; color: #334155; }
    .date { color: #64748b; font-size: 8.5pt; margin-bottom: 10px; }
    .subject { font-weight: 700; color: #0f172a; margin-bottom: 15px; font-size: 9.5pt; text-transform: uppercase; letter-spacing: 0.02em; }
    .body-content p { margin-bottom: 12px; text-align: justify; text-justify: inter-word; }
  </style>
</head>
<body>
  <div class="header">
    <div class="name">${escapeHtml(fullName)}</div>
    ${headline ? `<div class="headline">${escapeHtml(headline)}</div>` : ""}
    <div class="contact-info">
      <div class="contact-item">✉ ${escapeHtml(email)}</div>
      ${phoneNumber ? `<div class="contact-item">📞 ${escapeHtml(phoneNumber)}</div>` : ""}
    </div>
  </div>

  <div class="date">${escapeHtml(dateStr)}</div>

  <div class="recipient-info">
    <strong>Hiring Team</strong><br/>
    ${escapeHtml(companyName)}
  </div>

  <div class="subject">Subject: Application for ${escapeHtml(jobTitle)}</div>

  <div class="body-content">
    ${formattedParagraphs}
  </div>
</body>
</html>`;

    case "CREATIVE":
      return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: Letter; margin: 0; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 9pt; color: #2d3748; line-height: 1.5; }
    .layout { display: table; width: 100%; min-height: 11in; border-collapse: collapse; }
    .sidebar { display: table-cell; width: 220px; background-color: #0f172a; color: #e2e8f0; vertical-align: top; padding: 30px 20px; }
    .main-content { display: table-cell; background-color: #ffffff; vertical-align: top; padding: 40px 35px; }
    
    /* Sidebar Details */
    .sb-title { font-size: 7.5pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: #64748b; margin-top: 15px; margin-bottom: 4px; }
    .sb-value { font-size: 8pt; color: #f1f5f9; margin-bottom: 8px; word-break: break-all; }
    .sb-name { font-size: 14pt; font-weight: 900; color: #ffffff; line-height: 1.1; margin-bottom: 3px; }
    .sb-headline { font-size: 7.5pt; color: ${accentColor}; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 15px; }
    .sb-divider { height: 1px; background-color: #1e293b; margin: 15px 0; }

    /* Main Details */
    .header-block { margin-bottom: 20px; }
    .date { color: #718096; font-size: 8.5pt; margin-bottom: 15px; }
    .recipient { font-size: 9pt; color: #1a202c; font-weight: 600; margin-bottom: 2px; }
    .company { font-size: 9pt; color: #4a5568; margin-bottom: 15px; }
    .subject { font-size: 9.5pt; font-weight: 800; color: #0f172a; margin-bottom: 20px; border-left: 3px solid ${accentColor}; padding-left: 8px; }
    .body-content p { margin-bottom: 12px; color: #2d3748; }
  </style>
</head>
<body>
  <div class="layout">
    <div class="sidebar">
      <div class="sb-name">${escapeHtml(fullName)}</div>
      ${headline ? `<div class="sb-headline">${escapeHtml(headline)}</div>` : ""}
      
      <div class="sb-divider"></div>
      
      <div class="sb-title">Contact</div>
      <div class="sb-title" style="margin-top: 8px;">Email</div>
      <div class="sb-value">${escapeHtml(email)}</div>
      ${phoneNumber ? `<div class="sb-title">Phone</div><div class="sb-value">${escapeHtml(phoneNumber)}</div>` : ""}
    </div>
    
    <div class="main-content">
      <div class="date">${escapeHtml(dateStr)}</div>
      
      <div class="header-block">
        <div class="recipient">Hiring Team</div>
        <div class="company">${escapeHtml(companyName)}</div>
      </div>
      
      <div class="subject">Re: Application for ${escapeHtml(jobTitle)}</div>
      
      <div class="body-content">
        ${formattedParagraphs}
      </div>
    </div>
  </div>
</body>
</html>`;

    case "MINIMALIST":
      return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: Letter; margin: 0.8in 1.0in; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; font-size: 9.5pt; color: #27272a; line-height: 1.5; }
    .header { margin-bottom: 20px; }
    .name { font-size: 16pt; font-weight: 500; color: #09090b; letter-spacing: -0.02em; }
    .contact-line { font-size: 8.5pt; color: #71717a; margin-top: 3px; }
    .date { margin-bottom: 15px; font-size: 8.5pt; color: #71717a; }
    .recipient { font-size: 9pt; font-weight: 500; color: #09090b; margin-bottom: 15px; }
    .body-content p { margin-bottom: 12px; text-align: justify; }
  </style>
</head>
<body>
  <div class="header">
    <div class="name">${escapeHtml(fullName)}</div>
    <div class="contact-line">
      ${escapeHtml(email)} ${phoneNumber ? ` &bull; ${escapeHtml(phoneNumber)}` : ""}
    </div>
  </div>

  <div class="date">${escapeHtml(dateStr)}</div>

  <div class="recipient">
    Hiring Manager<br/>
    ${escapeHtml(companyName)}
  </div>

  <div style="font-weight: 500; margin-bottom: 15px; color: #09090b;">Re: Application for ${escapeHtml(jobTitle)}</div>

  <div class="body-content">
    ${formattedParagraphs}
  </div>
</body>
</html>`;

    case "CLASSIC":
    default:
      return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: Letter; margin: 0.6in 0.8in; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Georgia, 'Times New Roman', serif; font-size: 9.5pt; color: #111111; line-height: 1.45; }
    .sender-info { text-align: right; margin-bottom: 18px; font-size: 8.5pt; color: #444444; }
    .sender-name { font-family: Arial, sans-serif; font-size: 14pt; font-weight: bold; color: #111111; margin-bottom: 3px; }
    .recipient-info { margin-bottom: 15px; }
    .date { margin-bottom: 12px; }
    .subject { font-weight: bold; margin-bottom: 15px; font-size: 9.5pt; }
    .body-content p { margin-bottom: 12px; text-indent: 0px; text-align: justify; }
  </style>
</head>
<body>
  <div class="sender-info">
    <div class="sender-name">${escapeHtml(fullName)}</div>
    ${headline ? `<div style="font-style: italic; margin-bottom: 3px;">${escapeHtml(headline)}</div>` : ""}
    <div>Email: ${escapeHtml(email)}</div>
    ${phoneNumber ? `<div>Phone: ${escapeHtml(phoneNumber)}</div>` : ""}
  </div>

  <div class="date">${escapeHtml(dateStr)}</div>

  <div class="recipient-info">
    Hiring Committee<br/>
    ${escapeHtml(companyName)}
  </div>

  <div class="subject">SUBJECT: APPLICATION FOR THE POSITION OF ${escapeHtml(jobTitle.toUpperCase())}</div>

  <div class="body-content">
    ${formattedParagraphs}
  </div>
</body>
</html>`;
  }
}

export async function renderCoverLetterPdf(args: RenderCoverLetterArgs): Promise<Buffer> {
  const html = buildCoverLetterHtml(args);
  const isLocal = process.env.NODE_ENV !== "production";

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: null,
    executablePath: isLocal
      ? (process.env.CHROME_EXECUTABLE_PATH ?? await chromium.executablePath())
      : await chromium.executablePath(),
    headless: true,
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 816, height: 1056 });
    await page.setContent(html, { waitUntil: "networkidle2" });
    const pdf = await page.pdf({
      printBackground: true,
      preferCSSPageSize: true,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

export async function renderCoverLetterDocx(args: RenderCoverLetterArgs): Promise<Buffer> {
  const { fullName, email, phoneNumber, headline, content, jobTitle, companyName } = args;
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric"
  });

  const children: Paragraph[] = [];

  // Header Details (Classic Style for DOCX)
  children.push(
    new Paragraph({
      alignment: AlignmentType.RIGHT,
      spacing: { after: 120 },
      children: [
        new TextRun({ text: fullName, bold: true, size: 24 }),
        new TextRun({ text: headline ? `\n${headline}` : "", italics: true, size: 16 }),
        new TextRun({ text: `\nEmail: ${email}`, size: 16 }),
        new TextRun({ text: phoneNumber ? `\nPhone: ${phoneNumber}` : "", size: 16 }),
      ],
    })
  );

  // Date
  children.push(
    new Paragraph({
      spacing: { after: 120 },
      children: [new TextRun({ text: dateStr, size: 18 })],
    })
  );

  // Recipient
  children.push(
    new Paragraph({
      spacing: { after: 120 },
      children: [
        new TextRun({ text: "Hiring Manager / Recruitment Team\n", size: 18 }),
        new TextRun({ text: companyName, size: 18 }),
      ],
    })
  );

  // Subject
  children.push(
    new Paragraph({
      spacing: { after: 180 },
      children: [
        new TextRun({ text: `SUBJECT: APPLICATION FOR THE POSITION OF ${jobTitle.toUpperCase()}`, bold: true, size: 18 }),
      ],
    })
  );

  // Body content split by paragraph breaks
  const paragraphs = content.split(/\n\s*\n/);
  paragraphs.forEach((p) => {
    children.push(
      new Paragraph({
        spacing: { after: 120 },
        children: [new TextRun({ text: p.trim(), size: 18 })],
      })
    );
  });

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1000, right: 1000, bottom: 1000, left: 1000 }, // 0.7 inch
          },
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
